backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "experience"
    label: "Experience"
    folder: "src/pages/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "experience",
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Start Date", name: "startDate", widget: "string" }
      - { label: "End Date", name: "endDate", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Skills", name: "skills", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Demo", name: "demo", widget: "string" }
      - { label: "Github", name: "github", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Stack", name: "stack", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
